### ISSUE TITLE
还是有点BUG 老哥

### ISSUE THREAD

**Issue by LannYuu** [Curtion/douyu-gift#13]
小意见：
  我是每天设置的定时任务 到点了软件就会自动运行，就没管了 ，但是我发现 最近 一打开就显示任务完成 然后不会自动获取荧光棒 的数量 ，非得手动操作一下 他才开始触发任务

**Comment by Curtion** [comment]
软件逻辑在启动后会马上自动获取荧光棒，没有执行可能原因： 软件启动时系统的网络环境还没有准备好或者这不是软件正常启动。
现在还没有日志记录功能呢，所以你可以clone源码，运行 `yarn electron:serve` 进行手动调试。
如果不会的话，那么建议设置为延迟启动1分钟启动试试
