### ISSUE TITLE
为什么不能定时启动，然后完成任务后自动关闭啊？

### ISSUE THREAD

**Issue by wuwukaibukaigua** [Curtion/douyu-gift#17]
我因为开机时是没网的，所以只有在有网的时候定时启动，但是为什么开机自启可以完成任务后关闭，定时启动就不行啊？

**Comment by Curtion** [comment]
是使用的windows的计划任务吗？由于没有开发日志功能，所以你可以试着描述一下你的操作步骤，我试试看能不能重现问题。

**Comment by wuwukaibukaigua** [comment]
不，就是在软件任务配置上只有点了开机自启才能点任务完成后自动关闭，如果点定时运行，那任务完成自动关闭就是灰的，点不了。

**Comment by Curtion** [comment]
> 不，就是在软件任务配置上只有点了开机自启才能点任务完成后自动关闭，如果点定时运行，那任务完成自动关闭就是灰的，点不了。

这个定时功能是给无人值守的PC准备的。所以目前软件满足不了你的需求，后面可以考虑取消“自动启动”和”自动关闭“的关联，不过最近可能没有时间，在这之前你可以自行尝试一下。

**Comment by wuwukaibukaigua** [comment]
好的，谢谢
