### ISSUE TITLE
没有定时任务的功能吗

### ISSUE THREAD

**Issue by as1543100166** [Curtion/douyu-gift#2]
任务好像不会自动完成，必须重启软件

**Comment by Curtion** [comment]
现在没有自动领取荧光棒的功能，如果手动领取荧光棒的时机在启动软件之后，那么可以暂时手动切换左侧选项卡来刷新背包荧光棒，来实现不重启软件开启任务，后面会加上自动领取荧光棒的功能，为了防止频繁访问斗鱼接口引起账号异常，定时任务可能不会做。
