### ISSUE TITLE
yarn electron:build  提示 Cannot find module './App.vue'.

### ISSUE THREAD

**Issue by nileixing** [Curtion/douyu-gift#21]
yarn electron:build 
提示 Cannot find module './App.vue'.
Cannot find module '../views/home.vue'.
Cannot find module '../views/config.vue'.
Cannot find module '../views/about.vue'.

请问我这边是不是少装了什么环境

**Comment by Curtion** [comment]
你这边是不是非Windows环境吗？ 或者给一个完整的日志吧，也有可能是electron没有安装好，这个是需要挂梯子下载的

**Comment by nileixing** [comment]
是windows的，下载来生成好的exe是可以运行的，我想改下内容，试了下下yarn run build 是正常的，另一个yarn electron:build有相对路径的代码就会提示错误，我重新安装下electron试试
