### ISSUE TITLE
大佬 能不能安排个每周日续牌的选项

### ISSUE THREAD

**Issue by Nutshell-King** [Curtion/douyu-gift#24]
超级粉丝团的荧光棒周日才清零  而且周末亲密度1.5倍

**Comment by Curtion** [comment]
周赠送功能可能还得延后了，主要是这个不好测试。

**Comment by popsee** [comment]
我之前写了个类似的油猴脚本，搞了个简单粗暴的方法，逻辑是非周末每天送一根，如果是周末则全部平均送（因为周末双倍亲密度），核心加个if判断：
if(new Date().getDay()===0 || new Date().getDay()===6 )
但现在感觉还是麻烦，现在搞成nodejs纯后端的，丢到服务器上或云函数或github Action上更方便和省心，但碰到一个比较棘手的问题，荧光棒自动送没问题，但荧光棒需要点击页面背包领取才能有，后端模拟请求背包也没卵用，好像DY要某些其他的验证限制，不点页面就领不到荧光棒，这个就很难受！
不知道老兄现在你的领取荧光棒是怎么做的？找了下源码，没看到，如可能希望能告知下！十分感谢！

**Comment by Curtion** [comment]
> 我之前写了个类似的油猴脚本，搞了个简单粗暴的方法，逻辑是非周末每天送一根，如果是周末则全部平均送（因为周末双倍亲密度），核心加个if判断：
> if(new Date().getDay()===0 || new Date().getDay()===6 )
> 但现在感觉还是麻烦，现在搞成nodejs纯后端的，丢到服务器上或云函数或github Action上更方便和省心，但碰到一个比较棘手的问题，荧光棒自动送没问题，但荧光棒需要点击页面背包领取才能有，后端模拟请求背包也没卵用，好像DY要某些其他的验证限制，不点页面就领不到荧光棒，这个就很难受！
> 不知道老兄现在你的领取荧光棒是怎么做的？找了下源码，没看到，如可能希望能告知下！十分感谢！

领取礼物和请求背包没有关联，我这里是用electron开了一个隐藏的直播间，此时会自动领取礼物。我以前研究过这个问题，领取荧光棒和弹幕服务器有关系，斗鱼有两个和弹幕相关的服务，一个是弹幕列表服务器，一个是认证服务器，在通过认证服务器认证后，通过斗鱼的私有协议即可领取到荧光棒，建议从这个方向入手研究。

**Comment by popsee** [comment]
好的，十分感谢老哥，我去试试！

**Comment by popsee** [comment]
![续牌子](https://user-images.githubusercontent.com/13653691/117803944-c298f580-b289-11eb-8fd1-42c2189e1535.jpg)
果然是这样呀，太感谢老哥了，我加上DY的WebSockets连接（wss://wsproxy.douyu.com:6675）后，居然就自动领荧光棒了，确实不需要模拟请求背包（而且请求也没球用）。之后直接发请求送棒棒就OK了，一共不到五百行代码，丢到腾讯云函数上运行，server酱反馈，十分方便！每天定时跑，终于省心了！nice！
![C9F07AD9CDCDD0AC6F6DBCDDAB7BAB14](https://user-images.githubusercontent.com/13653691/117805314-67680280-b28b-11eb-9ca4-4c9fd2f8b1a5.png)
再次衷心感谢老哥的idea与反馈！
Thank  you so much!  bro!

**Comment by Curtion** [comment]
自定义时间段在新软件上实现了   https://github.com/Curtion/douyu-keep
