### ISSUE TITLE
不会自动送荧光棒了

### ISSUE THREAD

**Issue by FGFW** [Curtion/douyu-gift#27]
RT，需要修复

**Comment by Curtion** [comment]
我这边没有问题，可能是你的牌子中的某个直播间被封了？ 异常处理考虑加上

**Comment by FGFW** [comment]
> 我这边没有问题，可能是你的牌子中的某个直播间被封了？ 异常处理考虑加上

如果有个别被封,应该有其它房间可以送成功吧。我确认我手动给所有牌子房间都是能送上荧光棒的。

**Comment by FGFW** [comment]
怎么进调度模式呢，我看看输出信息之类的

**Comment by Curtion** [comment]
> 怎么进调度模式呢，我看看输出信息之类的

目前没有日志，目前只能通过yarn electron:serve进入开发模式看哪里有问题

**Comment by Curtion** [comment]
V1.3.2添加了日志记录功能 https://github.com/Curtion/douyu-gift/releases/tag/v1.3.2  ，如果此问题目前依然存在请上传脱敏后的日志，并重新open issue
