### ISSUE TITLE
不会自动送荧光棒了啊，无限循环但送不出去

### ISSUE THREAD

**Issue by xiangyuezc** [Curtion/douyu-gift#29]
大佬求修复

**Comment by FGFW** [comment]
你把进程都关一下再试试.
把比例填上,需要刚好是百分百.

**Comment by Curtion** [comment]
最近抽时间正在写日志的的功能，软件不能正常使用的情况下我建议先手动到每个直播间赠送一个进行测试，例如直播间已被关闭可能会导致这个问题，日志功能会和异常处理功能共同更新

**Comment by xiangyuezc** [comment]
大佬，所有直播间都能手动赠送的。我怀疑是不是斗鱼客户端授权挂了啊，但是不知道如何软件初始化重新登陆斗鱼。

**Comment by Curtion** [comment]
有一个切换账号的功能，在弹出页面中退出再重新登录；或者在配置页面点一下更新配置。如果仍然不行的话需要等日志更新了

**Comment by FGFW** [comment]
算法可以优化一下。比如让用户可以省略输入%号

**Comment by xiangyuezc** [comment]
感谢大佬们回复，前两天一直上不来github回复不及时。我在虚拟机上试了下，确定不是账号长期未登录导致的问题，期待更新。

**Comment by FGFW** [comment]
好像是需要手动更新数据的原因。
我第一次用没有点过更新数据，就不会自动送。
更新数据好像还会覆盖掉比例设置

**Comment by Curtion** [comment]
V1.3.2添加了日志记录功能 https://github.com/Curtion/douyu-gift/releases/tag/v1.3.2  ，如果此问题目前依然存在请上传脱敏后的日志，并重新open issue
