### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by w900316** [Curtion/douyu-gift#44]
为什么我挂在电脑上，设置的定时自动运行，每天到点了不会自动运行呢?运行日志里也没用

**Comment by Curtion** [comment]
已经收到问题，在测试复现后会被修复

**Comment by Curtion** [comment]
已经进行测试，未复现问题，但是新版本添加了自动运行日志功能，此处的自动运行是需要保持软件后台运行的。

https://github.com/Curtion/douyu-gift/releases/tag/v1.3.3

如果有问题请再进一步反馈
