### ISSUE TITLE
大佬,荧光棒自动赠送失败

### ISSUE THREAD

**Issue by null8me** [Curtion/douyu-gift#49]
![image](https://user-images.githubusercontent.com/84654117/145410983-40c16ede-9948-4e7b-b22e-fb90f604a5ca.png)
一直不断地重复显示,但是没有送出去

**Comment by Curtion** [comment]
看一下 `%USERPROFILE%\AppData\Roaming\douyu\logs\`其中的日志内容是什么？ 如果无法确定原因可以脱敏后发出来

**Comment by null8me** [comment]
![image](https://user-images.githubusercontent.com/84654117/145413633-271fe826-16d0-4333-aac5-fe9d4f8c2cad.png)
日志是这样的

**Comment by Curtion** [comment]
> ![image](https://user-images.githubusercontent.com/84654117/145413633-271fe826-16d0-4333-aac5-fe9d4f8c2cad.png) 日志是这样的

任务配置项正常的吗

**Comment by null8me** [comment]
任务配置项没有改动,都是默认的,因为我刚才手动赠送了荧光棒,只能明天测试了

**Comment by Curtion** [comment]
> 任务配置项没有改动,都是默认的,因为我刚才手动赠送了荧光棒,只能明天测试了

在人物配置项中需要手动设置分配的百分比，检查一下比例是不是没有填写。

**Comment by null8me** [comment]
填写了比例就好了,因为看提示说自动分配,之前就没有填,现在没问题了

**Comment by null8me** [comment]
填写了比例之后就正常了,之前因为看提示说自动分配,就没有填,现在没问题了,大佬加油啊,终于找到了全网唯一可用的保牌工具(大哭)!!!

**Comment by Curtion** [comment]
> 填写了比例之后就正常了,之前因为看提示说自动分配,就没有填,现在没问题了,大佬加油啊,终于找到了全网唯一可用的保牌工具(大哭)!!!

已经修改说明
