### ISSUE TITLE
大佬 何时支持自定义比例赠送荧光棒

### ISSUE THREAD

**Issue by vcan** [Curtion/douyu-gift#6]
打开了自定义赠送比例，发现修改完没用，看了半天的代码，发现好像没有自定义赠送的代码实现。
想问问大佬何时更新？谢谢

**Comment by Curtion** [comment]
确实是没有实现，如果需要这个功能的话会在近一周内进行更新

**Comment by vcan** [comment]
自定义赠送我手动根据房间号进行了修改，但是在mac上打包程序后报这个错误，调试半天搞不定。
我把'/config.db'修改成了'config.db'开发模式不报错了，但是打包完以后就这个错误。
大佬更新的时候能不能顺便看看这个问题。感谢
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/config.db'

**Comment by Curtion** [comment]
> 自定义赠送我手动根据房间号进行了修改，但是在mac上打包程序后报这个错误，调试半天搞不定。
> 我把'/config.db'修改成了'config.db'开发模式不报错了，但是打包完以后就这个错误。
> 大佬更新的时候能不能顺便看看这个问题。感谢
> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: ENOENT: no such file or directory, open '/config.db'

在windows上面的路径是`\\`，而在mac上路径是`/`，所以你可以尝试修改`background.ts`文件的第10行和13行，我没有MAC OS的电脑，无法进行测试，不过后续我会在Linux上进行测试，但在这之前你可以自行尝试一下。

**Comment by vcan** [comment]
感谢！问题解决，修改了下路径好了。
`let paths = process.execPath.split('/');
paths.pop();
let db = new Datastore({
  filename: path.join(paths.join('/'), '/config.db'),
  autoload: true
});`

**Comment by vcan** [comment]
建议把赠送逻辑从按百分比的模式换成数字的方式，荧光棒数量都是固定的，如果每天得到25个荧光棒，有四个牌子，按比例分配会导致剩下1个的情况，会导致一直重复的请求问题。

**Comment by Curtion** [comment]
[V1.1.0](https://github.com/Curtion/douyu-gift/releases/tag/v1.1.0)增加了这个功能，但是还没有进行测试。
