### ISSUE TITLE
希望能更改分配荧光棒的逻辑

### ISSUE THREAD

**Issue by Cairl** [Curtion/douyu-gift#61]
说实话，百分比分荧光棒挺鸡肋的，希望能改为大部分直播间只送1个荧光棒保牌，其余剩下的荧光棒全部统一送给某个直播间，不然百分比送的话荧光棒少的时候挺难分配的，而且会漏直播间

**Comment by Curtion** [comment]
下个版本做，下个版本同时应该会增加最小化启动

**Comment by Cairl** [comment]
感谢，希望也能同时修复下切换账号按钮失效的问题

**Comment by Curtion** [comment]
根据数量赠送和切换帐号功能在新软件上实现了   https://github.com/Curtion/douyu-keep
