### ISSUE TITLE
大佬能不能添加个后台运行

### ISSUE THREAD

**Issue by Begginm** [Curtion/douyu-gift#62]
不知道现在能不能后台运行，一直是在任务栏中开着不太方便，因为电脑是一直不关的。想的是像类似于微信qq那种放到托盘区不管他的那种，不知道可不可以做。这样就可以一直挂在后台不管

**Comment by Curtion** [comment]
新软件实现了托盘功能,可以使用新的   https://github.com/Curtion/douyu-keep
