### ISSUE TITLE
不会自动赠送BUG，需要重试才会生效

### ISSUE THREAD

**Issue by Curtion** [Curtion/douyu-gift#7]
已知BUG，等待修复，需要一段时间

**Comment by aaa11aa111** [comment]
还没更新吗

**Comment by Curtion** [comment]
> 还没更新吗

没有，因为时间原因会延后
可以暂时使用： https://github.com/Curtion/douyu-gift/releases/tag/v1.0.9 版本，这个版本正常使用，但是没有自定义比例功能
