### ISSUE TITLE
关于自动荧光棒

### ISSUE THREAD

**Issue by aaa11aa111** [Curtion/douyu-gift#8]
我想请问一下 我个人电脑是不关机的 请问有办法让他每天自动开启 然后 自动给荧光棒吗?
还是说我只要不勾选"任务完成后自动关闭"
就能保持让他后台运行并且自动执行?
![image](https://user-images.githubusercontent.com/21039366/83347864-c5027980-a2dc-11ea-8c4e-3a1e9cdfab3e.png)

**Comment by Curtion** [comment]
目前软件本身实现不了这个功能，但是可以使用windows的【计划任务程序】： https://www.cnblogs.com/vweiweiyixiaov/p/6611380.html  ，设置定时启动软件，同时勾选"任务完成后自动关闭"功能
